- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
  
    - name: Run multi-lined shell commands
      win_shell: |
 
           Copy-Item -Path C:\Users\Administrator\Downloads\result.html\* -ToSession $session -Destination 'C:\Users\Administrator\reports'

             
