- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
  
    - name: Run multi-lined shell commands
      win_shell: |
           Powershell
           Enable-PSRemoting -Force

             
