- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
    - name: Run powershell script
      win_shell: |
           powershell
           cd C:\Users\Administrator\Downloads
           echo y | pscp -r  -pw "WxRuwbjSU.%vp6lLL0J6ENcQL(s7p.Bo" C:\Users\Administrator\Downloads\result.html\* Administrator@172.31.33.86:C:\Users\Administrator\Downloads
           
