---
- name: copy file
  hosts: all
  become: true
  become_user: sample
  become_method: su
  become_exe: sudo su -
  
  gather_facts: false
  tasks:
  
    - name: copy file
      ansible.builtin.shell: |
             sudo sudo sshpass -p 'infotech@12' scp -r /home/sample/NRTC_JMeter ssh ansible@43.204.249.145:C:\\
