---
- name: copy file
  hosts: all
  become: true
  become_user: sample
  become_method: su
  become_exe: sudo su -
  
  gather_facts: false
  tasks:
  
    - name: copy file
      ansible.builtin.shell: |
             sudo sshpass -p 'VGn((KE?3@QbN!mocbySZucbLhnHuRBQ' scp -r /home/sample/NRTC_JMeter ssh Administrator@43.204.249.145:C:\
