- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
  
    - name: copy file
      ansible.builtin.shell: |
             Enable-PSRemoting -Force
             Set-Item wsman:\localhost\client\trustedhosts * -Confirm:$False
             Restart-Service WinRM
             $session= New-PSSession  -ComputerName 172.31.10.7 -Credential Administrator
