---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create container jmeter

      shell: |
         docker run -it --name jmeter harishpallapu/jmeter-3i
