---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create container jmeter

      docker_container:
        name: jmeter
        image: harishpallapu/jmeter-3i:latest
        state: started
