---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create container jmeter:
      shell: |
        docker run -it --name jmeter -w /jmeter/bin/project -v /root:/jmeter/bin/project harishpallapu/jmeter-3i:latest
