---
- name: Running Docker
  hosts: all
  become: true
  gather_facts: false
  
  vars_files:
     - variable.yml
  tasks:
    - name: pull an image
      ansible.builtin.shell: |
           Remove-Item -path ${pwd}\* -recurse -force
           docker run --rm --name test -v ${pwd}:C:\JMETER_PROJECT\project harishpallapu/coma:latest -Command "C:\JMETER_PROJECT\apache-jmeter-5.4.2\bin\jmeter.bat --version;cd project;git clone https://github.com/Poornateja2509/NRTC_JMeter.git;C:\JMETER_PROJECT\apache-jmeter-5.4.2\bin\jmeter.bat -n -t NRTC_JMeter/*.jmx -l result.jtl -e -o result.html;ls;pwd"
