---
- name: performance_testing
  hosts: all
  become: true
  become_user: sample
  become_method: su
  become_exe: sudo su -
  
  tasks:
    - name: pull an image
      ansible.builtin.shell: |
      #ansible.windows.win_powershell: |
           sudo sshpass -p 'infotech@12' ssh -o StrictHostKeyChecking=no ansible@43.205.111.22
           cd Downloads
           Remove-Item -path ${pwd}\* -recurse -force
    #       docker run --rm --name test -v ${pwd}:C:\JMETER_PROJECT\project harishpallapu/coma:latest -Command "C:\JMETER_PROJECT\apache-jmeter-5.4.2\bin\jmeter.bat --version;cd project;git clone https://github.com/Poornateja2509/NRTC_JMeter.git;C:\JMETER_PROJECT\apache-jmeter-5.4.2\bin\jmeter.bat -n -t NRTC_JMeter/*.jmx -l result.jtl -e -o result.html;ls;pwd"
